### convert .dot files generated by python to .png files, then merge them into a single .pdf file

if [ $# -eq 0 ]
    then
        echo "A filter must be selected."
        exit
fi

case $1 in
    dot)
        for file in ./*.dot
        do
            dot -T png "$file" > "$file".png
        done
        ;;

    neato)
        for file in ./*.dot
        do
            neato -T png "$file" > "$file".png
        done
        ;;

    twopi)
        for file in ./*.dot
        do
            twopi -T png "$file" > "$file".png
        done
        ;;

    circo)
        for file in ./*.dot
        do
            circo -T png "$file" > "$file".png
        done
        ;;

    fdp)
        for file in ./*.dot
        do
            fdp -T png "$file" > "$file".png
        done
        ;;

    sfdp)
        for file in ./*.dot
        do
            sfdp -T png "$file" > "$file".png
        done
        ;;

    patchwork)
        for file in ./*.dot
        do
            patchwork -T png "$file" > "$file".png
        done
        ;;
    *)
        echo "Invalid filter"
        exit
        ;;
esac

convert *.png graph.pdf
